apiVersion: v1
kind: Service
metadata:
  name: ticket-create-service
spec:
  type: NodePort
  selector:
    app: redmine-ticket-receiver
  ports:
    - protocol: "TCP"
      port: 8000
      nodePort: 32400  
